pipeline:
  build:
    image: golang
    commands:
      - go get github.com/tools/godep
      - godep restore
      - go build
      - go test
  publish:
    image: plugins/docker
    repo: nossas/bonde-redirect
    tags: latest
    when:
      event: [ tag ]
  notify:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: n_tech
    when:
      event: [ push, tag, deployment, pull_request ]
      status: [ success, failure ]

