pipeline:
  build:
    image: golang
    commands:
      - go get
      - go build
      - go test
  publish:
    image: plugins/docker
    repo: nossas/bonde-redirect
    tags: latest
    when:
      event: [ tag ]
  notify:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: n_tech
