pipeline:
  build:
    image: golang
    commands:
      - go get github.com/tools/godep
      - godep restore
      - go build
      - go test
    when:
      event: [push, tag]

  publish-docker-production:
    image: plugins/docker
    repo: nossas/bonde-redirect
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_TAG##v}
    when:
      status: success
      event: tag

  publish-docker-staging:
    image: plugins/docker
    repo: nossas/bonde-redirect
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_BRANCH}
    when:
      status: success
      branch: [hotfix-*, release-*, feature-*, develop]

  deploy-dokku-production:
    image: appleboy/drone-ssh
    host: redirect.bonde.org
    username: ubuntu
    secrets: [ ssh_key ]
    port: 22
    script:
      - sudo docker pull nossas/bonde-redirect:${DRONE_TAG##v}
      - sudo docker tag nossas/bonde-redirect:${DRONE_TAG##v} dokku/bonde-redirect:latest
      - dokku tags:deploy bonde-redirect latest
    when:
      status: success
      event: tag

  deploy-rancher-staging:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: staging/redirect
    docker_image: nossas/bonde-redirect:${DRONE_BRANCH}
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      branch: [hotfix-*, release-*, feature-*, develop]

  notify:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: bonde_bots 
    username: CI - ${DRONE_REPO_NAME}
    when:
      event: [ push, tag, build, publish, deployment, pull_request ]
      status: [ success, failure ]
