pipeline:
  build:
    image: golang
    commands:
      - go get github.com/tools/godep
      - godep restore
      - go build
      - go test
  publish:
    image: plugins/docker
    repo: nossas/bonde-redirect
    username: lpirola
    password: ${DOCKER_PASSWORD}
    when:
      event: [ tag ]
  deployment:
    image: appleboy/drone-ssh
    host: redirect.bonde.org
    username: ubuntu
    key: ${SSH_KEY}
    script:
      - sudo docker pull nossas/bonde-redirect:latest
      - sudo docker tag nossas/bonde-redirect:latest dokku/0-redirect:latest
      - dokku tags:deploy 0-redirect latest
    when:
      event: [ tag ]
  notify:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: n_tech
    when:
      event: [ push, tag, build, publish, deployment, pull_request ]
      status: [ success, failure ]
