pipeline:
  build:
    image: golang
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - cp -R . /go/src/app && cd /go/src/app && dep ensure
      - go build
      - go test
    when:
      event: [push, tag]

  publish-docker-production:
    image: plugins/docker
    repo: nossas/bonde-redirect
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_TAG##v}
    when:
      status: success
      event: tag

  publish-docker-staging:
    image: plugins/docker
    repo: nossas/bonde-redirect
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_BRANCH/\//-}
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, develop]

  deploy-rancher-production:
    image: peloton/drone-rancher
    timeout: 360
    docker_image: nossas/bonde-redirect
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    url: http://cluster.bonde.org
    service: bonde/redirect
    when:
      status: success
      event: tag

  deploy-rancher-staging:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: staging/redirect
    docker_image: nossas/bonde-redirect:${DRONE_BRANCH}
    confirm: true
    timeout: 360
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      branch: [hotfix-*, release-*, feature-*, develop]

  notify:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: bonde_bots
    username: CI - ${DRONE_REPO_NAME}
    when:
      event: [ push, tag, build, publish, deployment, pull_request ]
      status: [ success, failure ]
